name: CI Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: Bump Version
        id: bump
        uses: hugh-nguyen/cortex-cytoskeleton/.github/actions/bump_version@main
        with:
          latest_tag: ${{ needs.get_latest_tag.outputs.latest_tag }}

  build:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 --no-verify-ssl | docker login --username AWS --password-stdin 495599745704.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Build Docker Image
        run: |
          ECR_REPO="495599745704.dkr.ecr.ap-southeast-2.amazonaws.com/app1-service-a"
          TAG="${{ needs.bump_version.outputs.new_tag }}"

          echo "Building image with tag: $TAG"
          docker build -t "$ECR_REPO:$TAG" .
          docker push "$ECR_REPO:$TAG"

  tag_commit:
    needs: 
      - bump_version
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Tag Commit
        uses: hugh-nguyen/cortex-cytoskeleton/.github/actions/tag_commit@main
        with:
          new_tag: ${{ needs.bump_version.outputs.new_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
